// Comprehensive country dial codes for phone pickers worldwide
window.ARAMEX_COUNTRIES = [
  {name:"Afghanistan",code:"+93",flag:"🇦🇫"},
  {name:"Albania",code:"+355",flag:"🇦🇱"},
  {name:"Algeria",code:"+213",flag:"🇩🇿"},
  {name:"Andorra",code:"+376",flag:"🇦🇩"},
  {name:"Angola",code:"+244",flag:"🇦🇴"},
  {name:"Argentina",code:"+54",flag:"🇦🇷"},
  {name:"Armenia",code:"+374",flag:"🇦🇲"},
  {name:"Australia",code:"+61",flag:"🇦🇺"},
  {name:"Austria",code:"+43",flag:"🇦🇹"},
  {name:"Azerbaijan",code:"+994",flag:"🇦🇿"},
  {name:"Bahrain",code:"+973",flag:"🇧🇭"},
  {name:"Bangladesh",code:"+880",flag:"🇧🇩"},
  {name:"Belarus",code:"+375",flag:"🇧🇾"},
  {name:"Belgium",code:"+32",flag:"🇧🇪"},
  {name:"Benin",code:"+229",flag:"🇧🇯"},
  {name:"Bhutan",code:"+975",flag:"🇧🇹"},
  {name:"Bolivia",code:"+591",flag:"🇧🇴"},
  {name:"Bosnia and Herzegovina",code:"+387",flag:"🇧🇦"},
  {name:"Botswana",code:"+267",flag:"🇧🇼"},
  {name:"Brazil",code:"+55",flag:"🇧🇷"},
  {name:"Brunei",code:"+673",flag:"🇧🇳"},
  {name:"Bulgaria",code:"+359",flag:"🇧🇬"},
  {name:"Burkina Faso",code:"+226",flag:"🇧🇫"},
  {name:"Cambodia",code:"+855",flag:"🇰🇭"},
  {name:"Cameroon",code:"+237",flag:"🇨🇲"},
  {name:"Canada",code:"+1",flag:"🇨🇦"},
  {name:"Chile",code:"+56",flag:"🇨🇱"},
  {name:"China",code:"+86",flag:"🇨🇳"},
  {name:"Colombia",code:"+57",flag:"🇨🇴"},
  {name:"Congo",code:"+242",flag:"🇨🇬"},
  {name:"Costa Rica",code:"+506",flag:"🇨🇷"},
  {name:"Croatia",code:"+385",flag:"🇭🇷"},
  {name:"Cyprus",code:"+357",flag:"🇨🇾"},
  {name:"Czech Republic",code:"+420",flag:"🇨🇿"},
  {name:"Denmark",code:"+45",flag:"🇩🇰"},
  {name:"Egypt",code:"+20",flag:"🇪🇬"},
  {name:"Estonia",code:"+372",flag:"🇪🇪"},
  {name:"Ethiopia",code:"+251",flag:"🇪🇹"},
  {name:"Finland",code:"+358",flag:"🇫🇮"},
  {name:"France",code:"+33",flag:"🇫🇷"},
  {name:"Georgia",code:"+995",flag:"🇬🇪"},
  {name:"Germany",code:"+49",flag:"🇩🇪"},
  {name:"Ghana",code:"+233",flag:"🇬🇭"},
  {name:"Greece",code:"+30",flag:"🇬🇷"},
  {name:"Hong Kong",code:"+852",flag:"🇭🇰"},
  {name:"Hungary",code:"+36",flag:"🇭🇺"},
  {name:"Iceland",code:"+354",flag:"🇮🇸"},
  {name:"India",code:"+91",flag:"🇮🇳"},
  {name:"Indonesia",code:"+62",flag:"🇮🇩"},
  {name:"Iran",code:"+98",flag:"🇮🇷"},
  {name:"Iraq",code:"+964",flag:"🇮🇶"},
  {name:"Ireland",code:"+353",flag:"🇮🇪"},
  {name:"Israel",code:"+972",flag:"🇮🇱"},
  {name:"Italy",code:"+39",flag:"🇮🇹"},
  {name:"Japan",code:"+81",flag:"🇯🇵"},
  {name:"Jordan",code:"+962",flag:"🇯🇴"},
  {name:"Kazakhstan",code:"+7",flag:"🇰🇿"},
  {name:"Kenya",code:"+254",flag:"🇰🇪"},
  {name:"Kuwait",code:"+965",flag:"🇰🇼"},
  {name:"Lebanon",code:"+961",flag:"🇱🇧"},
  {name:"Libya",code:"+218",flag:"🇱🇾"},
  {name:"Luxembourg",code:"+352",flag:"🇱🇺"},
  {name:"Malaysia",code:"+60",flag:"🇲🇾"},
  {name:"Maldives",code:"+960",flag:"🇲🇻"},
  {name:"Malta",code:"+356",flag:"🇲🇹"},
  {name:"Mexico",code:"+52",flag:"🇲🇽"},
  {name:"Morocco",code:"+212",flag:"🇲🇦"},
  {name:"Nepal",code:"+977",flag:"🇳🇵"},
  {name:"Netherlands",code:"+31",flag:"🇳🇱"},
  {name:"New Zealand",code:"+64",flag:"🇳🇿"},
  {name:"Nigeria",code:"+234",flag:"🇳🇬"},
  {name:"Norway",code:"+47",flag:"🇳🇴"},
  {name:"Oman",code:"+968",flag:"🇴🇲"},
  {name:"Pakistan",code:"+92",flag:"🇵🇰"},
  {name:"Palestine",code:"+970",flag:"🇵🇸"},
  {name:"Philippines",code:"+63",flag:"🇵🇭"},
  {name:"Poland",code:"+48",flag:"🇵🇱"},
  {name:"Portugal",code:"+351",flag:"🇵🇹"},
  {name:"Qatar",code:"+974",flag:"🇶🇦"},
  {name:"Romania",code:"+40",flag:"🇷🇴"},
  {name:"Russia",code:"+7",flag:"🇷🇺"},
  {name:"Saudi Arabia",code:"+966",flag:"🇸🇦"},
  {name:"Senegal",code:"+221",flag:"🇸🇳"},
  {name:"Serbia",code:"+381",flag:"🇷🇸"},
  {name:"Singapore",code:"+65",flag:"🇸🇬"},
  {name:"South Africa",code:"+27",flag:"🇿🇦"},
  {name:"South Korea",code:"+82",flag:"🇰🇷"},
  {name:"Spain",code:"+34",flag:"🇪🇸"},
  {name:"Sri Lanka",code:"+94",flag:"🇱🇰"},
  {name:"Sudan",code:"+249",flag:"🇸🇩"},
  {name:"Sweden",code:"+46",flag:"🇸🇪"},
  {name:"Switzerland",code:"+41",flag:"🇨🇭"},
  {name:"Syria",code:"+963",flag:"🇸🇾"},
  {name:"Taiwan",code:"+886",flag:"🇹🇼"},
  {name:"Tanzania",code:"+255",flag:"🇹🇿"},
  {name:"Thailand",code:"+66",flag:"🇹🇭"},
  {name:"Tunisia",code:"+216",flag:"🇹🇳"},
  {name:"Turkey",code:"+90",flag:"🇹🇷"},
  {name:"Uganda",code:"+256",flag:"🇺🇬"},
  {name:"Ukraine",code:"+380",flag:"🇺🇦"},
  {name:"United Arab Emirates",code:"+971",flag:"🇦🇪"},
  {name:"United Kingdom",code:"+44",flag:"🇬🇧"},
  {name:"United States",code:"+1",flag:"🇺🇸"},
  {name:"Uzbekistan",code:"+998",flag:"🇺🇿"},
  {name:"Venezuela",code:"+58",flag:"🇻🇪"},
  {name:"Vietnam",code:"+84",flag:"🇻🇳"},
  {name:"Yemen",code:"+967",flag:"🇾🇪"},
  {name:"Zambia",code:"+260",flag:"🇿🇲"},
  {name:"Zimbabwe",code:"+263",flag:"🇿🇼"}
];

window.ARAMEX_COUNTRY_NAMES = window.ARAMEX_COUNTRIES.map(c => c.name).sort();

window.ARAMEX_OFFICES = [
  {city:"Dubai", country:"United Arab Emirates", address:"Sheikh Zayed Road, Al Quoz Industrial Area"},
  {city:"Abu Dhabi", country:"United Arab Emirates", address:"Mussafah Industrial Area"},
  {city:"Sharjah", country:"United Arab Emirates", address:"Industrial Area 6"},
  {city:"Riyadh", country:"Saudi Arabia", address:"Olaya Street, Al Olaya District"},
  {city:"Jeddah", country:"Saudi Arabia", address:"Prince Sultan Road"},
  {city:"Dammam", country:"Saudi Arabia", address:"King Fahd Road"},
  {city:"Amman", country:"Jordan", address:"Mecca Street, Al Rabieh"},
  {city:"Cairo", country:"Egypt", address:"Nasr City, Cairo"},
  {city:"Alexandria", country:"Egypt", address:"Smouha"},
  {city:"Kuwait City", country:"Kuwait", address:"Shuwaikh Industrial Area"},
  {city:"Manama", country:"Bahrain", address:"Seef District"},
  {city:"Doha", country:"Qatar", address:"Industrial Area"},
  {city:"Muscat", country:"Oman", address:"Al Ghubrah"},
  {city:"Beirut", country:"Lebanon", address:"Hamra Street"},
  {city:"Istanbul", country:"Turkey", address:"Ataşehir"},
  {city:"London", country:"United Kingdom", address:"Heathrow Cargo Centre"},
  {city:"Frankfurt", country:"Germany", address:"Frankfurt Airport Cargo City"},
  {city:"Paris", country:"France", address:"Roissy Charles de Gaulle"},
  {city:"New York", country:"United States", address:"JFK International Airport"},
  {city:"Los Angeles", country:"United States", address:"LAX Cargo"},
  {city:"Toronto", country:"Canada", address:"Pearson Airport"},
  {city:"Mumbai", country:"India", address:"Andheri East"},
  {city:"Delhi", country:"India", address:"Indira Gandhi International Airport"},
  {city:"Singapore", country:"Singapore", address:"Changi Airfreight Centre"},
  {city:"Hong Kong", country:"Hong Kong", address:"Chek Lap Kok"},
  {city:"Shanghai", country:"China", address:"Pudong International Airport"},
  {city:"Beijing", country:"China", address:"Capital International Airport"},
  {city:"Sydney", country:"Australia", address:"Sydney Airport"},
  {city:"Johannesburg", country:"South Africa", address:"OR Tambo International"},
  {city:"Nairobi", country:"Kenya", address:"Jomo Kenyatta International"},
  {city:"Lagos", country:"Nigeria", address:"Ikeja"},
  {city:"Casablanca", country:"Morocco", address:"Mohammed V Airport"}
];
